### ISSUE TITLE
Use git submodules to import dependent repositories

### ISSUE THREAD

**Issue by davidyuk** [aeternity/documentation-hub#220]
https://git-scm.com/book/en/v2/Git-Tools-Submodules
For example, for SDKs: https://github.com/aeternity/documentation-hub/tree/master/site/developer-tools
At least, this should make dependabot to don't track them.

**Comment by marc0olo** [comment]
I was looking into this topic recently and found this mkdocs plugin which allows us to do that quite easily:
- https://github.com/backstage/mkdocs-monorepo-plugin

I was testing it in a separate repository:
- https://github.com/marc0olo/mkdocs-submodule-playground

the only bug I identified is that the edit url of submodule pages cannot be provided correctly. the issue about that is here:
- https://github.com/backstage/mkdocs-monorepo-plugin/issues/45

**Comment by marc0olo** [comment]
@mradkov @nikita-fuchs FYI I am working on this now. I will add following repos with mkdocs initially:

- [ ] https://github.com/aeternity/protocol (mkdocs currently missing)
    - no WIP state present
- [x] https://github.com/aeternity/aeternity (mkdocs already configured correctly)
    - the current docs are hosted at https://docs.aeternity.io/en/stable/ using the ReadTheDocs Theme
- [ ] https://github.com/aeternity/aesophia (mkdocs currently missing)
    - there is an open PR where I can at least check and copy the mkdocs.yml (https://github.com/aeternity/aesophia/pull/282) - currently not sure if we need additional changes to the docs here
- [ ] https://github.com/aeternity/aepp-sdk-js (mkdocs available but needs to be fixed / improved)
    - there is a branch where this is being tackled by @nikita-fuchs (https://github.com/aeternity/aepp-sdk-js/tree/readTheDocs-optimized) but I am not sure if I can and will make use of it

When this is finished the maintainers of each repo are responsible to keep it up to date. The only thing we would need to figure out then is how to automate updates to the documentation hub based on changes in the repos of the submodules. But let's get this done first.

Ideally we include docs for other tools like https://github.com/aeternity/aepp-aeproject-js shortly after this is done.

I will probably make use of the Material theme here. We will see.

Probably I will make some additional changes wherever needed.

**Comment by marc0olo** [comment]
there are another 2 things to be aware of right now:
- `site_name` with spaces isn't allowed using the monorepo plugin (https://github.com/backstage/mkdocs-monorepo-plugin/issues/4)
   - the comments in the issue propose some workarounds for that
- the command `mkdocs serve` seems to be broken right now (https://github.com/backstage/mkdocs-monorepo-plugin/issues/49)

**Comment by marc0olo** [comment]
PR for aesophia is open now:
- https://github.com/aeternity/aesophia/pull/333

**Comment by marc0olo** [comment]
new (draft) PR for the protocol is open now:
- https://github.com/aeternity/protocol/pull/494
